package org.example.domain.entities;

/**
 * Security Test entity generated by LLM for specific OWASP vulnerabilities
 */
public class SecurityTest {
    private String id;
    private String name;
    private String description;
    private String testType;
    private String payload;
    private String expectedResult;
    private String actualResult;
    private boolean passed;
    private int severityScore;
    private String category;
    private String requestTemplate;
    private String responseValidation;

    public SecurityTest() {}

    public SecurityTest(String name, String testType, String payload) {
        this.id = generateId();
        this.name = name;
        this.testType = testType;
        this.payload = payload;
    }

    private String generateId() {
        return "TEST_" + System.currentTimeMillis() + "_" + (int)(Math.random() * 1000);
    }

    // Getters and Setters
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getTestType() { return testType; }
    public void setTestType(String testType) { this.testType = testType; }

    public String getPayload() { return payload; }
    public void setPayload(String payload) { this.payload = payload; }

    public String getExpectedResult() { return expectedResult; }
    public void setExpectedResult(String expectedResult) { this.expectedResult = expectedResult; }

    public String getActualResult() { return actualResult; }
    public void setActualResult(String actualResult) { this.actualResult = actualResult; }

    public boolean isPassed() { return passed; }
    public void setPassed(boolean passed) { this.passed = passed; }

    public int getSeverityScore() { return severityScore; }
    public void setSeverityScore(int severityScore) { this.severityScore = severityScore; }

    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }

    public String getRequestTemplate() { return requestTemplate; }
    public void setRequestTemplate(String requestTemplate) { this.requestTemplate = requestTemplate; }

    public String getResponseValidation() { return responseValidation; }
    public void setResponseValidation(String responseValidation) { this.responseValidation = responseValidation; }

    @Override
    public String toString() {
        return "SecurityTest{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", testType='" + testType + '\'' +
                ", passed=" + passed +
                ", severityScore=" + severityScore +
                '}';
    }
}
