@startuml
actor Client as C
participant "API Bank" as Bank

C -> Bank: POST /auth/bank-token (client_id, client_secret)
activate Bank
Bank -> C: access_token
deactivate Bank

C -> Bank: GET /accounts
activate Bank
Bank -> C: list of accounts
deactivate Bank

C -> Bank: GET /accounts/{card_account_id}
activate Bank
Bank -> C: account details (account_id, nickname, servicer)
deactivate Bank

@enduml