@startuml
actor Client as C
participant "API Bank" as Bank
participant "Internal Tokenization System" as ITS

C -> Bank: POST /auth/bank-token (client_id, client_secret)
activate Bank
Bank -> C: access_token
deactivate Bank

C -> Bank: GET /accounts
activate Bank
Bank -> C: list of accounts
deactivate Bank

C -> Bank: Select card account
C -> ITS: Request tokenization for account
activate ITS
ITS -> C: token
deactivate ITS

@enduml