/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the Spring Boot plugin
    id("org.springframework.boot") version "3.4.0"
    id("io.spring.dependency-management") version "1.1.6"
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Spring Boot Starters
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-websocket")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.boot:spring-boot-starter-webflux")

    // Database
    runtimeOnly("com.h2database:h2")

    // JSON Processing
    implementation("com.fasterxml.jackson.core:jackson-databind")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")

    // HTTP Client (Reactive)
    implementation("io.projectreactor.netty:reactor-netty")
    implementation("org.springframework:spring-webflux")

    // ONNX Runtime for Java
    implementation("com.microsoft.onnxruntime:onnxruntime:1.17.0")

    // Process Management and Utilities
    implementation("org.zeroturnaround:zt-exec:1.12")
    implementation("org.apache.commons:commons-lang3:3.14.0")
    implementation("commons-io:commons-io:2.15.1")

    // File Upload
    implementation("commons-fileupload:commons-fileupload:1.5")

    // Logging
    implementation("ch.qos.logback:logback-classic:1.4.14")

    // Basic OpenAPI support (using stable versions)
    implementation("org.openapitools:openapi-generator:7.4.0")
    implementation("io.swagger.parser.v3:swagger-parser-v3:2.1.22")
    implementation("io.swagger.parser.v2:swagger-parser-v2:2.1.22")
    
    // YAML and JSON processing
    implementation("org.yaml:snakeyaml:2.2")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.15.3")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.15.3")
    
    // HTTP client utilities
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
    
    // JSON Schema validation
    implementation("com.github.java-json-tools:json-schema-validator:2.2.14")
    implementation("com.github.java-json-tools:json-schema-core:1.2.14")

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("io.projectreactor:reactor-test")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.SecurityOrchestratorApplication"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
