package org.example.domain.dto.bpmn;

import org.example.domain.dto.bpmn.BpmnApiMappingRequestDto.BpmnApiMapping;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * Response DTO for BPMN to API mappings
 * Used for GET /api/analysis/bpmn/{diagramId}/mappings endpoint
 */
public class BpmnMappingsResponseDto {
    
    private String diagramId;
    private String apiSpecId;
    private String mappingId;
    private List<BpmnMapping> mappings;
    private MappingSummary summary;
    private Map<String, Object> mappingMetadata;
    private LocalDateTime createdAt;
    private LocalDateTime lastUpdated;
    private String status; // "DRAFT", "VALIDATED", "APPROVED", "DEPRECATED"
    private int confidenceScore;
    private List<String> warnings;
    private List<String> errors;
    
    public BpmnMappingsResponseDto() {}
    
    public BpmnMappingsResponseDto(String diagramId, String apiSpecId, String mappingId,
                                  List<BpmnMapping> mappings, MappingSummary summary,
                                  Map<String, Object> mappingMetadata, LocalDateTime createdAt,
                                  LocalDateTime lastUpdated, String status, int confidenceScore,
                                  List<String> warnings, List<String> errors) {
        this.diagramId = diagramId;
        this.apiSpecId = apiSpecId;
        this.mappingId = mappingId;
        this.mappings = mappings;
        this.summary = summary;
        this.mappingMetadata = mappingMetadata;
        this.createdAt = createdAt;
        this.lastUpdated = lastUpdated;
        this.status = status;
        this.confidenceScore = confidenceScore;
        this.warnings = warnings;
        this.errors = errors;
    }
    
    /**
     * Creates a mock response for demonstration
     */
    public static BpmnMappingsResponseDto createMock(String diagramId, String apiSpecId) {
        BpmnMappingsResponseDto response = new BpmnMappingsResponseDto();
        response.setDiagramId(diagramId);
        response.setApiSpecId(apiSpecId);
        response.setMappingId("mapping_" + diagramId + "_" + System.currentTimeMillis());
        response.setMappings(createMockMappings());
        response.setSummary(createMockSummary());
        response.setMappingMetadata(Map.of(
            "totalElements", 12,
            "mappedElements", 10,
            "unmappedElements", 2,
            "autoGenerated", true,
            "manualReviewed", false
        ));
        response.setCreatedAt(LocalDateTime.now().minusHours(2));
        response.setLastUpdated(LocalDateTime.now().minusMinutes(30));
        response.setStatus("DRAFT");
        response.setConfidenceScore(85);
        response.setWarnings(List.of(
            "Some mappings have low confidence scores",
            "Manual review recommended for complex transformations"
        ));
        return response;
    }
    
    public static class BpmnMapping {
        private String mappingId;
        private BpmnApiMapping bpmnApiMapping;
        private Double confidence;
        private String validationStatus; // "VALID", "WARNING", "ERROR"
        private List<String> validationMessages;
        private String reasoning;
        private Map<String, Object> mappingData;
        private LocalDateTime createdAt;
        private LocalDateTime validatedAt;
        
        public BpmnMapping() {}
        
        public BpmnMapping(String mappingId, BpmnApiMapping bpmnApiMapping, Double confidence,
                          String validationStatus, List<String> validationMessages, String reasoning,
                          Map<String, Object> mappingData, LocalDateTime createdAt, LocalDateTime validatedAt) {
            this.mappingId = mappingId;
            this.bpmnApiMapping = bpmnApiMapping;
            this.confidence = confidence;
            this.validationStatus = validationStatus;
            this.validationMessages = validationMessages;
            this.reasoning = reasoning;
            this.mappingData = mappingData;
            this.createdAt = createdAt;
            this.validatedAt = validatedAt;
        }
        
        // Getters and setters
        public String getMappingId() { return mappingId; }
        public void setMappingId(String mappingId) { this.mappingId = mappingId; }
        
        public BpmnApiMapping getBpmnApiMapping() { return bpmnApiMapping; }
        public void setBpmnApiMapping(BpmnApiMapping bpmnApiMapping) { this.bpmnApiMapping = bpmnApiMapping; }
        
        public Double getConfidence() { return confidence; }
        public void setConfidence(Double confidence) { this.confidence = confidence; }
        
        public String getValidationStatus() { return validationStatus; }
        public void setValidationStatus(String validationStatus) { this.validationStatus = validationStatus; }
        
        public List<String> getValidationMessages() { return validationMessages; }
        public void setValidationMessages(List<String> validationMessages) { this.validationMessages = validationMessages; }
        
        public String getReasoning() { return reasoning; }
        public void setReasoning(String reasoning) { this.reasoning = reasoning; }
        
        public Map<String, Object> getMappingData() { return mappingData; }
        public void setMappingData(Map<String, Object> mappingData) { this.mappingData = mappingData; }
        
        public LocalDateTime getCreatedAt() { return createdAt; }
        public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
        
        public LocalDateTime getValidatedAt() { return validatedAt; }
        public void setValidatedAt(LocalDateTime validatedAt) { this.validatedAt = validatedAt; }
    }
    
    public static class MappingSummary {
        private int totalElements;
        private int mappedElements;
        private int unmappedElements;
        private int highConfidenceMappings;
        private int mediumConfidenceMappings;
        private int lowConfidenceMappings;
        private double averageConfidence;
        private List<String> unmappedReasons;
        
        public MappingSummary() {}
        
        public MappingSummary(int totalElements, int mappedElements, int unmappedElements,
                            int highConfidenceMappings, int mediumConfidenceMappings, int lowConfidenceMappings,
                            double averageConfidence, List<String> unmappedReasons) {
            this.totalElements = totalElements;
            this.mappedElements = mappedElements;
            this.unmappedElements = unmappedElements;
            this.highConfidenceMappings = highConfidenceMappings;
            this.mediumConfidenceMappings = mediumConfidenceMappings;
            this.lowConfidenceMappings = lowConfidenceMappings;
            this.averageConfidence = averageConfidence;
            this.unmappedReasons = unmappedReasons;
        }
        
        // Getters and setters
        public int getTotalElements() { return totalElements; }
        public void setTotalElements(int totalElements) { this.totalElements = totalElements; }
        
        public int getMappedElements() { return mappedElements; }
        public void setMappedElements(int mappedElements) { this.mappedElements = mappedElements; }
        
        public int getUnmappedElements() { return unmappedElements; }
        public void setUnmappedElements(int unmappedElements) { this.unmappedElements = unmappedElements; }
        
        public int getHighConfidenceMappings() { return highConfidenceMappings; }
        public void setHighConfidenceMappings(int highConfidenceMappings) { this.highConfidenceMappings = highConfidenceMappings; }
        
        public int getMediumConfidenceMappings() { return mediumConfidenceMappings; }
        public void setMediumConfidenceMappings(int mediumConfidenceMappings) { this.mediumConfidenceMappings = mediumConfidenceMappings; }
        
        public int getLowConfidenceMappings() { return lowConfidenceMappings; }
        public void setLowConfidenceMappings(int lowConfidenceMappings) { this.lowConfidenceMappings = lowConfidenceMappings; }
        
        public double getAverageConfidence() { return averageConfidence; }
        public void setAverageConfidence(double averageConfidence) { this.averageConfidence = averageConfidence; }
        
        public List<String> getUnmappedReasons() { return unmappedReasons; }
        public void setUnmappedReasons(List<String> unmappedReasons) { this.unmappedReasons = unmappedReasons; }
    }
    
    // Utility methods
    public boolean hasWarnings() {
        return warnings != null && !warnings.isEmpty();
    }
    
    public boolean hasErrors() {
        return errors != null && !errors.isEmpty();
    }
    
    public boolean isFullyMapped() {
        return summary != null && summary.getUnmappedElements() == 0;
    }
    
    public boolean isHighQuality() {
        return confidenceScore >= 80 && !hasErrors();
    }
    
    private static List<BpmnMapping> createMockMappings() {
        BpmnApiMapping mapping1 = new BpmnApiMapping(
            "task_001", "User Registration Task", "UserTask",
            "/api/users", "POST", "createUser", "direct", 0.92, null,
            "Direct mapping to user creation API", false
        );
        
        BpmnApiMapping mapping2 = new BpmnApiMapping(
            "task_002", "Send Welcome Email", "ServiceTask",
            "/api/emails", "POST", "sendWelcomeEmail", "transformation", 0.78, 
            Map.of("template", "welcome", "delay", "immediate"),
            "Transformation required for email parameters", false
        );
        
        return List.of(
            new BpmnMapping("map_001", mapping1, 0.92, "VALID", null,
                          "High confidence direct mapping based on operation name and HTTP method",
                          Map.of("dataFlow", "direct"), LocalDateTime.now().minusHours(2), LocalDateTime.now().minusMinutes(30)),
            new BpmnMapping("map_002", mapping2, 0.78, "WARNING", 
                          List.of("Transformation required - manual review recommended"),
                          "Medium confidence transformation mapping",
                          Map.of("transformationType", "parameter_mapping"), LocalDateTime.now().minusHours(1), null)
        );
    }
    
    private static MappingSummary createMockSummary() {
        return new MappingSummary(12, 10, 2, 7, 2, 1, 0.85,
                                List.of("No matching API endpoint found", "Element type not supported by API"));
    }
    
    // Getters and setters
    public String getDiagramId() { return diagramId; }
    public void setDiagramId(String diagramId) { this.diagramId = diagramId; }
    
    public String getApiSpecId() { return apiSpecId; }
    public void setApiSpecId(String apiSpecId) { this.apiSpecId = apiSpecId; }
    
    public String getMappingId() { return mappingId; }
    public void setMappingId(String mappingId) { this.mappingId = mappingId; }
    
    public List<BpmnMapping> getMappings() { return mappings; }
    public void setMappings(List<BpmnMapping> mappings) { this.mappings = mappings; }
    
    public MappingSummary getSummary() { return summary; }
    public void setSummary(MappingSummary summary) { this.summary = summary; }
    
    public Map<String, Object> getMappingMetadata() { return mappingMetadata; }
    public void setMappingMetadata(Map<String, Object> mappingMetadata) { this.mappingMetadata = mappingMetadata; }
    
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    
    public LocalDateTime getLastUpdated() { return lastUpdated; }
    public void setLastUpdated(LocalDateTime lastUpdated) { this.lastUpdated = lastUpdated; }
    
    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
    
    public int getConfidenceScore() { return confidenceScore; }
    public void setConfidenceScore(int confidenceScore) { this.confidenceScore = confidenceScore; }
    
    public List<String> getWarnings() { return warnings; }
    public void setWarnings(List<String> warnings) { this.warnings = warnings; }
    
    public List<String> getErrors() { return errors; }
    public void setErrors(List<String> errors) { this.errors = errors; }
}